### ISSUE TITLE
Music is not working.

### ISSUE THREAD

**Issue by Shepelzz** [plasmoapp/pv-addon-lavaplayer-lib#13]
```
[22:07:17 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:07:19 INFO]: Loaded 7 recipes
[22:07:20 INFO]: Starting minecraft server version 1.20.1
[22:07:20 INFO]: Loading properties
[22:07:20 INFO]: This server is running Purpur version git-Purpur-1996 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: fa3166a on HEAD)
[22:07:20 INFO]: Server Ping Player Sample Count: 12
[22:07:20 INFO]: Using 4 threads for Netty based IO
[22:07:20 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 6 worker threads, and gen parallelism of 6 threads
[22:07:21 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[22:07:21 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[22:07:21 WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[22:07:21 WARN]: [Pufferfish] Debug: Java: 17.0.10, test run: true
[22:07:21 INFO]: Default game type: SURVIVAL
[22:07:21 INFO]: Generating keypair
[22:07:21 INFO]: Starting Minecraft server on *:25565
[22:07:21 INFO]: Using default channel type
[22:07:21 INFO]: Paper: Using Java compression from Velocity.
[22:07:21 INFO]: Paper: Using Java cipher from Velocity.
[22:07:22 INFO]: [SpigotLibraryLoader] [TempAfk] Loading 2 libraries... please wait
[22:07:22 INFO]: [SpigotLibraryLoader] [TempAfk] Loaded library D:\MC\SERVER\POST_RELEASE\libraries\com\mysql\mysql-connector-j\8.0.33\mysql-connector-j-8.0.33.jar
[22:07:22 INFO]: [SpigotLibraryLoader] [TempAfk] Loaded library D:\MC\SERVER\POST_RELEASE\libraries\com\google\protobuf\protobuf-java\3.21.9\protobuf-java-3.21.9.jar
[22:07:22 INFO]: [SpigotLibraryLoader] [TempAfk] Loaded library D:\MC\SERVER\POST_RELEASE\libraries\org\mariadb\jdbc\mariadb-java-client\3.1.4\mariadb-java-client-3.1.4.jar
[22:07:22 INFO]: [PlaceholderAPI] Loading server plugin PlaceholderAPI v2.11.5
[22:07:22 INFO]: [LuckPerms] Loading server plugin LuckPerms v5.4.98
[22:07:22 INFO]: [PlasmoVoice] Loading server plugin PlasmoVoice v2.0.8
[22:07:22 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[22:07:22 INFO]: [ProtocolLib] Loading server plugin ProtocolLib v5.1.0
[22:07:23 INFO]: [pv-addon-lavaplayer-lib] Loading server plugin pv-addon-lavaplayer-lib v1.0.6
[22:07:23 INFO]: [spark] Loading server plugin spark v1.10.60
[22:07:23 INFO]: [TempAfk] Loading server plugin TempAfk v1.0.0
[22:07:23 INFO]: [pv-addon-discs] Loading server plugin pv-addon-discs v1.0.5
[22:07:23 INFO]: Server permissions file permissions.yml is empty, ignoring it
[22:07:23 INFO]: [LuckPerms] Enabling LuckPerms v5.4.98
[22:07:24 INFO]: [96m       [36m __    [0m
[22:07:24 INFO]: [96m  |    [36m|__)   [32mLuckPerms[0m [96mv5.4.98[0m
[22:07:24 INFO]: [96m  |___ [36m|      [90mRunning on Bukkit - Purpur[0m
[22:07:24 INFO]: 
[22:07:24 INFO]: [LuckPerms] Loading configuration...
[22:07:24 INFO]: [LuckPerms] Loading storage provider... [H2]
[22:07:24 INFO]: [LuckPerms] Loading internal permission managers...
[22:07:24 INFO]: [LuckPerms] Performing initial data load...
[22:07:24 INFO]: [LuckPerms] Successfully enabled. (took 1233ms)
[22:07:24 INFO]: [PlasmoVoice] Enabling PlasmoVoice v2.0.8
[22:07:24 INFO]: [PlasmoVoice] LuckPerms permissions listener attached
[22:07:25 INFO]: [PlasmoVoice] pv-addon-lavaplayer-lib v1.0.6 by Apehum loaded
[22:07:25 INFO]: [PlasmoVoice] pv-addon-discs v1.0.5 by KPidS loaded
[22:07:25 INFO]: [PlasmoVoice] UDP server is started on /[0:0:0:0:0:0:0:0]:25565
[22:07:25 INFO]: [PlaceholderAPI] Successfully registered internal expansion: plasmovoice [2.0.8]
[22:07:25 INFO]: [Vault] Enabling Vault v1.7.3-b131
[22:07:25 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[22:07:25 INFO]: [Vault] Enabled Version 1.7.3-b131
[22:07:25 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[22:07:25 INFO]: [ProtocolLib] Enabling ProtocolLib v5.1.0
[22:07:25 INFO]: [pv-addon-lavaplayer-lib] Enabling pv-addon-lavaplayer-lib v1.0.6
[22:07:25 INFO]: [pv-addon-discs] Enabling pv-addon-discs v1.0.5
[22:07:26 INFO]: Preparing level "world"
[22:07:26 INFO]: Preparing start region for dimension minecraft:overworld
[22:07:26 INFO]: Time elapsed: 254 ms
[22:07:26 INFO]: Preparing start region for dimension minecraft:the_nether
[22:07:26 INFO]: Time elapsed: 19 ms
[22:07:26 INFO]: Preparing start region for dimension minecraft:the_end
[22:07:26 INFO]: Time elapsed: 18 ms
[22:07:26 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.5
[22:07:27 INFO]: [PlaceholderAPI] Fetching available expansion information...
[22:07:27 INFO]: [spark] Enabling spark v1.10.60
[22:07:27 INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[22:07:27 INFO]: [spark] Starting background profiler...
[22:07:27 INFO]: [spark] The async-profiler engine is not supported for your os/arch (windows11/amd64), so the built-in Java engine will be used instead.
[22:07:27 INFO]: [PlaceholderAPI] Successfully registered internal expansion: spark [1.10.60]
[22:07:27 INFO]: [spark] Registered PlaceholderAPI placeholders
[22:07:27 INFO]: [TempAfk] Enabling TempAfk v1.0.0
[22:07:27 INFO]: [TempAfk] {SQL} starting SQL ...
[22:07:27 INFO]: [TempAfk] {SQL} Connecting to SQLITE Database...
[22:07:28 INFO]: [TempAfk] {SQL} successfully connected to Database.
[22:07:28 WARN]: [TempAfk] An Economy Plugin is missing!
[22:07:28 INFO]: [PlaceholderAPI] Successfully registered internal expansion: TempAfk [1.0.0]
[22:07:28 INFO]: [TempAfk] PlacerHolderAPI was found and registered!
[22:07:28 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[22:07:28 INFO]: [33m0 placeholder hook(s) registered![0m
[22:07:28 INFO]: Running delayed init tasks
[22:07:28 INFO]: Done (7.699s)! For help, type "help"
[22:07:28 INFO]: [Vault] Checking for Updates ... 
[22:07:28 INFO]: [Vault] No new version available
[22:07:48 INFO]: UUID of player MrShmel is f287e9db-219a-4aad-ae02-544c82a005f5
[22:07:52 INFO]: [93mMrShmel joined the game[0m
[22:07:52 INFO]: MrShmel[/127.0.0.1:63119] logged in with entity id 256 at ([world]8.555834540670372, 110.0, 11.642826084491018)
[22:08:11 INFO]: MrShmel issued server command: /disc burn https://music.youtube.com/watch?v=5anLPw0Efmo&si=5VbUqyvGYflDKTnP
[22:08:11 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] YouTube auth tokens can't be retrieved because email and password is not set in YoutubeAudioSourceManager, age restricted videos will throw exceptions.
[22:08:12 INFO]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] Updating YouTube visitor id (current is null).
[22:08:12 INFO]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAccessTokenTracker] Updating YouTube visitor id succeeded, new one is Cgs1YUV2RERiZnhJSSisvaivBjIKCgJVQRIEGgAgRjoKIIaX7qvA1Yf1ZQ%3D%3D, next update will be after 600 seconds.
[22:08:12 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager] Error in loading item https://music.youtube.com/watch?v=5anLPw0Efmo&si=5VbUqyvGYflDKTnP
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:240) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:252) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:248) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:101) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:66) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:44) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:216) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:147) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:428) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:410) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:208) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:842) ~[?:?]
	Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.0
  os.arch: amd64
  os.name: Windows 11
  os.version: 10.0
  java.vendor: Oracle Corporation
  java.version: 17.0.10
  java.runtime.version: 17.0.10+11-LTS-240
  java.vm.version: 17.0.10+11-LTS-240
Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:66) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	... 14 more
Caused by: java.io.IOException: Invalid status code for video page response: 400
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:157) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:228) ~[pv-addon-lavaplayer-lib-1.0.6.jar:?]
	... 14 more
[22:08:19 INFO]: MrShmel lost connection: Disconnected
[22:08:20 INFO]: [93mMrShmel left the game[0m

```

**Comment by Shepelzz** [comment]
Herre i found probably fix
https://github.com/lavalink-devs/lavaplayer/pull/70

Pls take a look

**Comment by Shepelzz** [comment]
@KPidS @Apehum 
please update dev.arbjerg:lavaplayer to last 2.1.0
