### ISSUE TITLE
Music is not playing

### ISSUE THREAD

**Issue by Harroybay** [plasmoapp/pv-addon-lavaplayer-lib#14]
**You insert a record into the player and this error comes out**

### [10:26:55 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of VSyuPgN70dg
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavaplayer.version: 495ea87beef35b161fc14138ab3523ecb97ba684-SNAPSHOT
os.arch: amd64
os.name: Linux
os.version: 5.4.0-153-generic
java.vendor: Azul Systems, Inc.
java.version: 21.0.2
java.runtime.version: 21.0.2+13-LTS
java.vm.version: 21.0.2+13-LTS
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.mozilla.javascript.Scriptable
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.TypeInfo.getClassFromInternalName(TypeInfo.java:207) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.TypeInfo.merge(TypeInfo.java:137) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.SuperBlock.mergeState(SuperBlock.java:119) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.SuperBlock.merge(SuperBlock.java:88) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.flowInto(ClassFileWriter.java:1814) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.executeBlock(ClassFileWriter.java:1732) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.executeWorkList(ClassFileWriter.java:1656) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.verify(ClassFileWriter.java:1561) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.generate(ClassFileWriter.java:1434) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter.stopMethod(ClassFileWriter.java:258) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(BodyCodegen.java:64) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:289) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:175) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:95) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileImpl(Context.java:2415) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileString(Context.java:1369) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileString(Context.java:1357) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.evaluateString(Context.java:1135) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:118) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipher.transform(YoutubeSignatureCipher.java:56) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:122) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:90) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
... 4 more
Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.Scriptable
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:?]
at java.lang.Class.forName(Class.java:421) ~[?:?]
at java.lang.Class.forName(Class.java:412) ~[?:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.TypeInfo.getClassFromInternalName(TypeInfo.java:205) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.TypeInfo.merge(TypeInfo.java:137) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.SuperBlock.mergeState(SuperBlock.java:119) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.SuperBlock.merge(SuperBlock.java:88) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.flowInto(ClassFileWriter.java:1814) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.executeBlock(ClassFileWriter.java:1732) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.executeWorkList(ClassFileWriter.java:1656) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.verify(ClassFileWriter.java:1561) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter$StackMapTable.generate(ClassFileWriter.java:1434) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.classfile.ClassFileWriter.stopMethod(ClassFileWriter.java:258) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.BodyCodegen.generateBodyCode(BodyCodegen.java:64) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.generateCode(Codegen.java:289) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.compileToClassFile(Codegen.java:175) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.optimizer.Codegen.compile(Codegen.java:95) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileImpl(Context.java:2415) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileString(Context.java:1369) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.compileString(Context.java:1357) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.Context.evaluateString(Context.java:1135) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.org.mozilla.javascript.engine.RhinoScriptEngine.eval(RhinoScriptEngine.java:118) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:262) ~[java.scripting:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipher.transform(YoutubeSignatureCipher.java:56) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:122) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:90) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:44) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.7.jar:?]
... 4 more

**Comment by Apehum** [comment]
Try with the latest version of prerelease: https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.7
