### ISSUE TITLE
Music doesn't play (Not success status code: 403)

### ISSUE THREAD

**Issue by cosmunn** [plasmoapp/pv-addon-lavaplayer-lib#24]
Same as issue #22, but still happening on version 1.0.10. Tried with YouTube and Dropbox links, happens with both.

```
[su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of anNTvgrhbL0
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 6.2.0-33-generic
  java.vendor: Amazon.com Inc.
  java.version: 21.0.3
  java.runtime.version: 21.0.3+9-LTS
  java.vm.version: 21.0.3+9-LTS
Caused by: java.lang.RuntimeException: Not success status code: 403
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at java.base/java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.base/java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        at pv-addon-lavaplayer-lib-1.0.10.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
        ... 4 more
```

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs#common-issues
