### ISSUE TITLE
lateinit property voiceServer has not been initialized

### ISSUE THREAD

**Issue by InchanterX** [plasmoapp/pv-addon-lavaplayer-lib#25]
I encountered a problem that when I launch the addon, it does not start, giving me this error. I have PlasmoVoice-Paper-2.0.4. How to fix it?

`[00:53:49 ERROR]: Error occurred while enabling pv-addon-discs v1.1.0 (Is it up to date?)
su.plo.voice.libs.kotlin.UninitializedPropertyAccessException: lateinit property voiceServer has not been initialized
        at su.plo.voice.discs.DiscsPlugin.getVoiceServer(DiscsPlugin.kt:40) ~[pv-addon-discs-1.1.0.jar:?]
        at su.plo.voice.discs.DiscsPlugin.loadConfig(DiscsPlugin.kt:109) ~[pv-addon-discs-1.1.0.jar:?]
        at su.plo.voice.discs.DiscsPlugin.onEnable(DiscsPlugin.kt:70) ~[pv-addon-discs-1.1.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[00:53:49 INFO]: [pv-addon-discs] Disabling pv-addon-discs v1.1.0
[00:53:49 INFO]: [PlasmoVoice] Addon pv-addon-discs v1.1.0 by KPidS, Apehum unloaded`

**Comment by apehum** [comment]
Well, really really late response

But if anyone will encounter the same issue, solution is to install latest versions of everything (Plasmo Voice, pv-addon-discs, pv-addon-lavaplayer-lib)
