### ISSUE TITLE
Problematic YouTube player script [pv-addon-discs not play]

### ISSUE THREAD

**Issue by MaoDoBan** [plasmoapp/pv-addon-lavaplayer-lib#27]
[08:46:46] [Server thread/INFO]: MaoDoBan issued server command: /disc burn https://www.youtube.com/watch?v=oowBXzfcl90
[08:46:46] [lava-daemon-pool-info-loader-2-thread-1/ERROR]: [su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.cipher.SignatureCipherManager] Problematic YouTube player script /s/player/d2e656ee/player_ias.vflset/pt_BR/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script15944686254006539491.js
[08:46:50] [lava-daemon-pool-playback-1-thread-1/ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of oowBXzfcl90
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.4
  os.arch: aarch64
  os.name: Linux
  os.version: 5.15.0-1016-oracle
  java.vendor: Eclipse Adoptium
  java.version: 17.0.7
  java.runtime.version: 17.0.7+7
  java.vm.version: 17.0.7+7
Caused by: java.lang.RuntimeException: Not success status code: 403
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at java.io.DataInputStream.readByte(DataInputStream.java:271) ~[?:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.10.jar:?]
	... 4 more

**Comment by thejenja** [comment]
Fixed in [1.0.11 Pre-release](https://github.com/plasmoapp/pv-addon-lavaplayer-lib/releases/tag/1.0.11)
