### ISSUE TITLE
Version 1.0.11 not play a disc from pv-addon-discs

### ISSUE THREAD

**Issue by MaoDoBan** [plasmoapp/pv-addon-lavaplayer-lib#29]
paper-1.20.4-497
PlasmoVoice-Paper-2.0.10
pv-addon-lavaplayer-lib-1.0.11
pv-addon-discs-1.0.7

When I tried to play a disc with a youtube link on it:

```
[13:05:27 ERROR]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Error in playback of N8Oxa_R3pUA
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation: 
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 5.15.0-78-generic
  java.vendor: Amazon.com Inc.
  java.version: 21.0.3
  java.runtime.version: 21.0.3+9-LTS
  java.vm.version: 21.0.3+9-LTS
Caused by: java.lang.RuntimeException: su.plo.voice.lavaplayer.libs.org.apache.http.conn.ConnectTimeoutException: Connect to rr12---sn-pmcg-bg0z.googlevideo.com:443 [rr12---sn-pmcg-bg0z.googlevideo.com/104.237.170.33] failed: Connect timed out
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:57) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        ... 4 more
Caused by: su.plo.voice.lavaplayer.libs.org.apache.http.conn.ConnectTimeoutException: Connect to rr12---sn-pmcg-bg0z.googlevideo.com:443 [rr12---sn-pmcg-bg0z.googlevideo.com/104.237.170.33] failed: Connect timed out
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:150) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:73) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:121) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        ... 4 more
        Suppressed: su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator$AdditionalDetails: Encountered when opening a connection with the following details:
  host: https://rr12---sn-pmcg-bg0z.googlevideo.com:443
  localAddress: <unspecified>
  remoteAddress: rr12---sn-pmcg-bg0z.googlevideo.com/104.237.170.33:443
  connectTimeout: 3000
  triedAddresses: rr12---sn-pmcg-bg0z.googlevideo.com/104.237.170.33
Caused by: java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:751) ~[?:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connectWithDestination(ExtendedConnectionOperator.java:145) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.http.ExtendedConnectionOperator.connect(ExtendedConnectionOperator.java:69) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.HttpInterface.execute(HttpInterface.java:73) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:121) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at java.io.DataInputStream.readUnsignedByte(DataInputStream.java:295) ~[?:?]
        at java.io.DataInputStream.readByte(DataInputStream.java:275) ~[?:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:46) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:88) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        at su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[pv-addon-lavaplayer-lib-1.0.11.jar:?]
        ... 4 more
```

**Comment by MaoDoBan** [comment]
Now the disc play normally (magic?), but on the server console appears this error:
```
[06:06:38 ERROR]: [su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.cipher.SignatureCipherManager] Problematic YouTube player script /s/player/b12cc44b/player_ias.vflset/pt_BR/base.js detected (issue detected with script: no n function match). Dumped to /tmp/lavaplayer-yt-player-script17503566704718439060.js
```

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs#common-issues
