### ISSUE TITLE
ds

### ISSUE THREAD

**Issue by stripuhadvaa** [plasmoapp/pv-addon-lavaplayer-lib#36]
[18:46:34 INFO]: [su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.http.YoutubeAccessTokenTracker] Updating YouTube visitor id succeeded, new one is CgtOSWlFUVlmZkd4cyiJ1cu7BjIKCgJERRIEEgAgZDoMCAEgrJXnh5bRurln, next update will be after 600 seconds.
[18:46:35 WARN]: [su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor] Suspicious exception for playback of bVvdPMyY3tk
su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
        at pv-addon-lavaplayer-lib-1.1.2.jar/su.plo.voice.lavaplayer.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:104) ~[pv-addon-lavaplayer-lib-1.1.2.jar:?]
        at pv-addon-lavaplayer-lib-1.1.2.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[pv-addon-lavaplayer-lib-1.1.2.jar:?]
        at pv-addon-lavaplayer-lib-1.1.2.jar/su.plo.voice.lavaplayer.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[pv-addon-lavaplayer-lib-1.1.2.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1595) ~[?:?]

**Comment by apehum** [comment]
https://github.com/plasmoapp/pv-addon-discs#common-issues
